{% set name = "okonomiyaki" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6fa4fec7750a160c400f1da92397c43fed0765d161f16a74ef7daafd0e951d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs >=16.1.0
    - jsonschema >=2.5.1
    - six >=1.9.0
    - zipfile2 >=0.0.12

test:
  imports:
    - okonomiyaki

about:
  home: https://github.com/enthought/okonomiyaki
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Okonomiyaki is an experimental library aimed at consolidating a lot of our low-level code used for Enthought's eggs.

extra:
  recipe-maintainers:
    - hmaarrfk
