{% set name = "okonomiyaki" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ec08623adc80c901e42060ac7db9962fc8b91adb48be00425d7376a09225331

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs >=16.1.0
    - jsonschema >=2.5.1
    - six >=1.9.0
    - zipfile2 >=0.0.12

test:
  imports:
    - okonomiyaki

about:
  home: https://github.com/enthought/okonomiyaki
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Okonomiyaki is an experimental library aimed at consolidating a lot of our low-level code used for Enthought's eggs."

extra:
  recipe-maintainers:
    - hmaarrfk
