travis:
  secure:
    BINSTAR_TOKEN: eBVgrDPfd+xnwq/uSidY07GjkNqqGxuw8ZUOW4CdT3FW/sK0BBE+hR4vr5hH7T5tkA/7y3tttBP3hSKnyI5EEIGsYTFI0E9wm0GXBOuRkG8jbUWc7hccQYyFyyIlJJ0w55JiFIoHW04lU1rE8s0z+ivm36nJ9+1U2a6fq/5OlxeKT/Ambo8QzMI8umMq+PCUGF1ZO3Bn4AQMwtmmuqAJwU8buWC0LfQ0RN0cXoU4ULFiQdJ17ld6kK9PTB4l1PGjmzNPWUq4C2OAAm3xSVaFQfpZLBDxdG1tqmgtvBE+7JSpcOSQdlwnNE3Z4nFrFbLW5bP0a33Sbk3F+HRaFmFyRJNx/IlXxY5LcfWGs78pih6QwdhGETGJLWqECpOkN868/+qGwjhZ93LyO/2rNi4HBhEka9tN875F7IwLPmPzlIY1/phWCfzfDXcqDlnqHDNqSci4WC7PGe/987O+fHaRMR1cxBRsdhdzu16kylbSgiysLrEK5eeLqCYSIXiu2HP7+jBanjmZCx8EKrf0wt+T1lQ6jNNYS580Hul4AF5IG+InUgBcdNG4pjGriKKHrcIlZlrbZS02YDa0QoUoejBhO2V72b7aq6MflureSjl25VkS4kG1C2mnKlHU6SHiZz0yAHfY/mJj8H9r8rkTUPZOrwNbN5WG/uKcZ88P3+Z9ZWE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
